### ISSUE TITLE
Rename `RgbHttpJsonRpc` into `RgbJsonRpc`

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/invoices#4]

**Comment by nicbus** [comment]
I think the `ConsignmentEndpoint` should provide enough information to be used for exchanging a consignment

given that JSON-RPC can work over other protocols, like WebSocket, it should make sense to include the `Http` part in order to tell it apart from other implementations, e.g. `RgbWebsocketJsonRpc`

**Comment by dr-orlovsky** [comment]
Oh right, never thought that JSON-RPC can be performed over WebSocket!
